name: Maven Build
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        config-file: ./.github/codeql/codeql-config.yml
    - name: Build with Maven
      run: mvn clean test
    - name: Publish JavaDoc
      run: mvn site -Pjavadoc
      env:
        GITHUB_TOKEN: ${{ github.token }}
