name: Java CI with Maven
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install GPG key
      run: |
        cat <(echo -e "${{ secrets.GPG_KEY }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Publish to GitHub Packages Apache Maven
      run: mvn --batch-mode -Dgpg.passphrase=${{ secrets.GPG_PASS }} deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
